---
- name: Create the Azure Windows Virtual Machine
  hosts: localhost
  connection: local
  tasks:

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ win_vm_name }}"
        os_type: Windows
        vm_size: "{{ win_vm_size }}"
        admin_username: "{{ win_admin_user }}"
        admin_password: "{{ win_admin_password }}"
        network_interfaces: "{{ win_nic_name }}"
        tags:
          "name": "{{ win_vm_name }}"
          "demo": "true"
          "os": "windows"
          "username": "{{ win_admin_user }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: "{{ win_vm_sku }}"
          version: latest

    # Added as per https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible
    - name: Create VM script extension to enable HTTPS WinRM listener
      azure_rm_virtualmachineextension:
        name: winrm-wf-extension
        resource_group: "{{ resource_group_name }}"
        virtual_machine_name: "{{ win_vm_name }}"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.9'
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/stable-2.12/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true
